name: phonation
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  flutter_tts: ^3.7.0
  speech_to_text: ^6.1.1
  google_speech: ^2.2.0
  provider: ^6.0.5
  assets_audio_player: ^3.0.6
  just_audio: ^0.9.33
  cupertino_icons: ^1.0.5
  picovoice_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Black.ttf
        - asset: assets/fonts/merriweather/Merriweather-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/merriweather/Merriweather-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Light.ttf
        - asset: assets/fonts/merriweather/Merriweather-LightItalic.ttf
          style: italic
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
    - family: Karma
      fonts:
        - asset: assets/fonts/karma/Karma-Bold.ttf
        - asset: assets/fonts/karma/Karma-Light.ttf
        - asset: assets/fonts/karma/Karma-Medium.ttf
        - asset: assets/fonts/karma/Karma-Regular.ttf
        - asset: assets/fonts/karma/Karma-SemiBold.ttf

  assets:
    - assets/img/
    - assets/json/
    - assets/audio/
